{{- if eq (include "xrelease.createSecret" .) "true" }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "xrelease.secretsName" . }}
  labels:
    {{- include "xrelease.labels" . | nindent 4 }}
type: Opaque
stringData:
  {{- if .Values.secrets.apiKey }}
  XRELEASE_API_KEY: {{ .Values.secrets.apiKey | quote }}
  {{- end }}
  {{- if .Values.secrets.databaseUrl }}
  XRELEASE_DATABASE_URL: {{ .Values.secrets.databaseUrl | quote }}
  {{- end }}
  {{- if .Values.secrets.webhookSecret }}
  XRELEASE_WEBHOOK_SECRET: {{ .Values.secrets.webhookSecret | quote }}
  {{- end }}
  {{- if .Values.secrets.expressAccessToken }}
  XRELEASE_EXPRESS_ACCESS_TOKEN: {{ .Values.secrets.expressAccessToken | quote }}
  {{- end }}
  {{- if .Values.secrets.configEncryptionKey }}
  XRELEASE_CONFIG_ENCRYPTION_KEY: {{ .Values.secrets.configEncryptionKey | quote }}
  {{- end }}
  {{- if .Values.secrets.sessionSecret }}
  XRELEASE_SESSION_SECRET: {{ .Values.secrets.sessionSecret | quote }}
  {{- end }}
  {{- if .Values.secrets.adminUser }}
  XRELEASE_ADMIN_USER: {{ .Values.secrets.adminUser | quote }}
  {{- end }}
  {{- if .Values.secrets.adminPassword }}
  XRELEASE_ADMIN_PASSWORD: {{ .Values.secrets.adminPassword | quote }}
  {{- end }}
{{- end }}
