//! Normalize inline desired-state secrets into `*_env` refs + [`SecretWrite`]s.
//!
//! Desired documents in `config_revision.content` keep structure and env-var
//! **names** only. Values are sealed in `app_secret` and cached in
//! [`crate::config::vault`] after persist.

use serde::Serialize;

use crate::config::{
    detect_desired_format, parse_desired_document, Config, DesiredFormat, NotifierConfig,
    SourceConfig,
};
use crate::error::StoreError;

/// One secret to upsert into `app_secret` / the process vault.
#[derive(Debug, Clone, PartialEq, Eq)]
pub struct SecretWrite {
    /// Env-var style name referenced by `*_env` in the desired document.
    pub name: String,
    /// Plaintext value.
    pub value: String,
}

/// Move inline secrets into vault refs. Mutates `config` in place.
///
/// Returns writes that the apply path must persist via
/// [`crate::store::Store::upsert_app_secrets`]. Does **not** touch the process
/// vault — validate/dry-run must stay side-effect free.
#[must_use]
pub fn normalize_secrets_to_refs(
    config: &mut Config,
    organization: Option<&str>,
) -> Vec<SecretWrite> {
    let mut writes = Vec::new();
    for (index, source) in config.sources.iter_mut().enumerate() {
        normalize_source_token(source, index, organization, &mut writes);
    }
    for (index, notifier) in config.notifiers.iter_mut().enumerate() {
        normalize_notifier(notifier, index, organization, &mut writes);
    }
    writes
}

/// Collect every non-empty `*_env` ref name from a desired-state document.
#[must_use]
pub fn collect_secret_env_refs(config: &Config) -> std::collections::HashSet<String> {
    use crate::config::{NotifierConfig, SourceConfig};

    let mut refs = std::collections::HashSet::new();
    let mut push = |value: &Option<String>| {
        if let Some(name) = value
            .as_deref()
            .map(str::trim)
            .filter(|name| !name.is_empty())
        {
            refs.insert(name.to_owned());
        }
    };

    for source in &config.sources {
        match source {
            SourceConfig::Github(c) | SourceConfig::Codeberg(c) => push(&c.token_env),
            SourceConfig::Gitea(c) => push(&c.token_env),
            SourceConfig::Gitlab(c) => push(&c.token_env),
            SourceConfig::Bitbucket(c) => push(&c.token_env),
            SourceConfig::Docker(c) => push(&c.token_env),
            SourceConfig::Ghcr(c) | SourceConfig::Quay(c) | SourceConfig::Ecr(c) => {
                push(&c.token_env);
            }
            _ => {}
        }
    }

    for notifier in &config.notifiers {
        match notifier {
            NotifierConfig::Apprise(n) => push(&n.urls_env),
            NotifierConfig::Webhook(n) => {
                push(&n.url_env);
                push(&n.secret_env);
                push(&n.headers_env);
            }
            NotifierConfig::Express(n) => push(&n.access_token_env),
            NotifierConfig::Novu(n) => push(&n.api_key_env),
            NotifierConfig::Slack(n) => {
                push(&n.webhook_url_env);
                push(&n.bot_token_env);
            }
            NotifierConfig::Telegram(n) => push(&n.bot_token_env),
            NotifierConfig::Smtp(n) => push(&n.password_env),
            NotifierConfig::Nats(n) => push(&n.url_env),
            NotifierConfig::Rabbitmq(n) => push(&n.url_env),
            NotifierConfig::Kafka(_) => {}
        }
    }
    refs
}

/// True when `name` was auto-generated by [`normalize_secrets_to_refs`] for
/// this apply scope (safe to delete from `app_secret` when no longer referenced).
#[must_use]
pub fn is_ui_managed_secret_name(name: &str, organization: Option<&str>) -> bool {
    let name = name.trim();
    if !name.starts_with("XRELEASE_UI_") {
        return false;
    }
    match organization.map(str::trim).filter(|org| !org.is_empty()) {
        Some(org) => {
            let mut prefix = String::from("XRELEASE_UI_");
            push_sanitized(&mut prefix, org);
            prefix.push('_');
            name.starts_with(&prefix)
        }
        // Whole-document auto names: `XRELEASE_UI_SRC_…` / `XRELEASE_UI_N_…`.
        None => name.starts_with("XRELEASE_UI_SRC_") || name.starts_with("XRELEASE_UI_N_"),
    }
}

/// UI-managed env names present in `previous` but not in `next` (orphan GC).
#[must_use]
pub fn stale_ui_managed_secrets(
    previous: &std::collections::HashSet<String>,
    next: &std::collections::HashSet<String>,
    organization: Option<&str>,
) -> Vec<String> {
    let mut stale: Vec<String> = previous
        .iter()
        .filter(|name| !next.contains(*name))
        .filter(|name| is_ui_managed_secret_name(name, organization))
        .cloned()
        .collect();
    stale.sort();
    stale
}

/// Parse `raw`, normalize secrets, return the refs-only wire document + writes.
///
/// # Errors
/// Returns [`StoreError::Other`] when parse or serialize fails.
pub fn normalize_document_for_storage(
    raw: &str,
    organization: Option<&str>,
) -> Result<(String, Vec<SecretWrite>), StoreError> {
    let format = detect_desired_format(raw);
    let mut config = parse_desired_document(raw)
        .map_err(|err| StoreError::Other(format!("config secret normalize: parse: {err}")))?;
    let writes = normalize_secrets_to_refs(&mut config, organization);
    let content = serialize_desired_only(format, &config)?;
    Ok((content, writes))
}

fn take_inline(value: &mut String) -> Option<String> {
    let trimmed = value.trim();
    // Reject GET placeholders and partial markers (`amqp://<redacted>@host`) so
    // they never land in `app_secret` when restore/match fails.
    if trimmed.is_empty() || trimmed == "<redacted>" || trimmed.contains("<redacted>") {
        value.clear();
        return None;
    }
    Some(std::mem::take(value))
}

fn take_optional_inline(value: &mut Option<String>) -> Option<String> {
    let inner = value.as_mut()?;
    let taken = take_inline(inner)?;
    *value = None;
    Some(taken)
}

fn ensure_env_name(existing: &mut Option<String>, generated: String) -> String {
    if let Some(name) = existing
        .as_deref()
        .map(str::trim)
        .filter(|name| !name.is_empty())
    {
        return name.to_owned();
    }
    *existing = Some(generated.clone());
    generated
}

fn auto_name(organization: Option<&str>, parts: &[&str]) -> String {
    let mut out = String::from("XRELEASE_UI");
    if let Some(org) = organization.map(str::trim).filter(|org| !org.is_empty()) {
        out.push('_');
        push_sanitized(&mut out, org);
    }
    for part in parts {
        out.push('_');
        push_sanitized(&mut out, part);
    }
    out
}

fn push_sanitized(out: &mut String, raw: &str) {
    for ch in raw.chars() {
        if ch.is_ascii_alphanumeric() {
            out.push(ch.to_ascii_uppercase());
        } else {
            out.push('_');
        }
    }
}

/// Stable-ish identity for auto vault names (prefer name / team tag / chat id
/// over list index so reordering 30 channels does not reshuffle secrets).
fn notifier_identity(notifier: &NotifierConfig, index: usize) -> String {
    if let Some(name) = notifier_label(notifier) {
        return truncate_slug(&name, 40);
    }
    let tag = notifier
        .routing_tags()
        .into_iter()
        .find(|tag| !tag.trim().is_empty());
    let tip = notifier_stable_tip(notifier);
    let kind = notifier_kind_slug(notifier);
    let mut parts: Vec<String> = Vec::new();
    if let Some(tag) = tag {
        parts.push(truncate_slug(tag.trim(), 24));
    }
    parts.push(kind.to_owned());
    if let Some(tip) = tip {
        parts.push(truncate_slug(&tip, 24));
    } else {
        parts.push(format!("I{index}"));
    }
    parts.join("_")
}

fn notifier_label(notifier: &NotifierConfig) -> Option<String> {
    let name = match notifier {
        NotifierConfig::Apprise(_) => None,
        NotifierConfig::Webhook(n) => n.name.as_deref(),
        NotifierConfig::Express(n) => n.name.as_deref(),
        NotifierConfig::Novu(n) => n.name.as_deref(),
        NotifierConfig::Slack(n) => n.name.as_deref(),
        NotifierConfig::Telegram(n) => n.name.as_deref(),
        NotifierConfig::Smtp(n) => n.name.as_deref(),
        NotifierConfig::Kafka(n) => n.name.as_deref(),
        NotifierConfig::Nats(n) => n.name.as_deref(),
        NotifierConfig::Rabbitmq(n) => n.name.as_deref(),
    }?;
    let trimmed = name.trim();
    (!trimmed.is_empty()).then(|| trimmed.to_owned())
}

fn notifier_kind_slug(notifier: &NotifierConfig) -> &'static str {
    match notifier {
        NotifierConfig::Apprise(_) => "APPRISE",
        NotifierConfig::Webhook(_) => "WEBHOOK",
        NotifierConfig::Express(_) => "EXPRESS",
        NotifierConfig::Novu(_) => "NOVU",
        NotifierConfig::Slack(_) => "SLACK",
        NotifierConfig::Telegram(_) => "TELEGRAM",
        NotifierConfig::Smtp(_) => "SMTP",
        NotifierConfig::Kafka(_) => "KAFKA",
        NotifierConfig::Nats(_) => "NATS",
        NotifierConfig::Rabbitmq(_) => "RABBITMQ",
    }
}

fn notifier_stable_tip(notifier: &NotifierConfig) -> Option<String> {
    let tip = match notifier {
        NotifierConfig::Apprise(n) => n
            .config_key
            .as_deref()
            .or(n.tag.as_deref())
            .or(Some(n.endpoint.as_str())),
        NotifierConfig::Webhook(n) => (!n.url.trim().is_empty()).then_some(n.url.as_str()),
        NotifierConfig::Express(n) => Some(n.group_chat_id.as_str()),
        NotifierConfig::Novu(n) => Some(n.workflow.as_str()),
        NotifierConfig::Slack(n) => (!n.channel.trim().is_empty()).then_some(n.channel.as_str()),
        NotifierConfig::Telegram(n) => Some(n.chat_id.as_str()),
        NotifierConfig::Smtp(n) => Some(n.host.as_str()),
        NotifierConfig::Kafka(n) => Some(n.topic.as_str()),
        NotifierConfig::Nats(n) => Some(n.subject.as_str()),
        NotifierConfig::Rabbitmq(n) => Some(n.routing_key.as_str()),
    }?;
    let trimmed = tip.trim();
    (!trimmed.is_empty() && trimmed != "<redacted>" && !trimmed.contains("<redacted>"))
        .then(|| trimmed.to_owned())
}

fn source_identity(source: &SourceConfig, index: usize) -> String {
    let tip = match source {
        SourceConfig::Github(c) | SourceConfig::Codeberg(c) => Some(c.repo.as_str()),
        SourceConfig::Gitea(c) => Some(c.repo.as_str()),
        SourceConfig::Gitlab(c) => Some(c.project.as_str()),
        SourceConfig::Bitbucket(c) => Some(c.repo.as_str()),
        SourceConfig::Docker(c) => Some(c.image.as_str()),
        SourceConfig::Ghcr(c) | SourceConfig::Quay(c) | SourceConfig::Ecr(c) => {
            Some(c.image.as_str())
        }
        SourceConfig::Feed(c) => Some(c.url.as_str()),
        SourceConfig::Pypi(c)
        | SourceConfig::Npm(c)
        | SourceConfig::Cargo(c)
        | SourceConfig::Maven(c)
        | SourceConfig::Nuget(c)
        | SourceConfig::Hex(c)
        | SourceConfig::Rubygems(c)
        | SourceConfig::Packagist(c)
        | SourceConfig::Yarn(c)
        | SourceConfig::Cpan(c) => Some(c.name.as_str()),
        SourceConfig::Artifacthub(c) => Some(c.name.as_str()),
    };
    tip.map(|value| truncate_slug(value, 48))
        .filter(|value| !value.is_empty())
        .unwrap_or_else(|| format!("I{index}"))
}

fn truncate_slug(raw: &str, max_chars: usize) -> String {
    let mut out = String::new();
    push_sanitized(&mut out, raw);
    while out.contains("__") {
        out = out.replace("__", "_");
    }
    let trimmed = out.trim_matches('_');
    if trimmed.is_empty() {
        return String::new();
    }
    trimmed.chars().take(max_chars).collect()
}

fn push_write(writes: &mut Vec<SecretWrite>, name: String, value: String) {
    if name.trim().is_empty() || value.trim().is_empty() {
        return;
    }
    if let Some(existing) = writes.iter_mut().find(|write| write.name == name) {
        existing.value = value;
        return;
    }
    writes.push(SecretWrite { name, value });
}

fn normalize_source_token(
    source: &mut SourceConfig,
    index: usize,
    organization: Option<&str>,
    writes: &mut Vec<SecretWrite>,
) {
    let identity = source_identity(source, index);
    let (token, token_env) = match source {
        SourceConfig::Github(c) => (&mut c.token, &mut c.token_env),
        SourceConfig::Codeberg(c) => (&mut c.token, &mut c.token_env),
        SourceConfig::Gitea(c) => (&mut c.token, &mut c.token_env),
        SourceConfig::Gitlab(c) => (&mut c.token, &mut c.token_env),
        SourceConfig::Bitbucket(c) => (&mut c.token, &mut c.token_env),
        SourceConfig::Docker(c) => (&mut c.token, &mut c.token_env),
        SourceConfig::Ghcr(c) => (&mut c.token, &mut c.token_env),
        SourceConfig::Quay(c) => (&mut c.token, &mut c.token_env),
        SourceConfig::Ecr(c) => (&mut c.token, &mut c.token_env),
        _ => return,
    };
    let Some(value) = take_optional_inline(token) else {
        return;
    };
    let name = ensure_env_name(
        token_env,
        auto_name(organization, &["SRC", &identity, "TOKEN"]),
    );
    push_write(writes, name, value);
}

fn normalize_notifier(
    notifier: &mut NotifierConfig,
    index: usize,
    organization: Option<&str>,
    writes: &mut Vec<SecretWrite>,
) {
    let identity = notifier_identity(notifier, index);
    match notifier {
        NotifierConfig::Apprise(n) => {
            let urls = std::mem::take(&mut n.urls);
            let live: Vec<String> = urls
                .into_iter()
                .filter(|url| {
                    let trimmed = url.trim();
                    !trimmed.is_empty()
                        && trimmed != "<redacted>"
                        && !trimmed.contains("<redacted>")
                })
                .collect();
            if live.is_empty() {
                return;
            }
            let name = ensure_env_name(
                &mut n.urls_env,
                auto_name(organization, &["N", &identity, "APPRISE_URLS"]),
            );
            let value = serde_json::to_string(&live).unwrap_or_default();
            push_write(writes, name, value);
        }
        NotifierConfig::Webhook(n) => {
            if let Some(value) = take_inline(&mut n.url) {
                let name = ensure_env_name(
                    &mut n.url_env,
                    auto_name(organization, &["N", &identity, "WEBHOOK_URL"]),
                );
                push_write(writes, name, value);
            }
            if let Some(value) = take_inline(&mut n.secret) {
                let name = ensure_env_name(
                    &mut n.secret_env,
                    auto_name(organization, &["N", &identity, "WEBHOOK_SECRET"]),
                );
                push_write(writes, name, value);
            }
            let headers = std::mem::take(&mut n.headers);
            let live: std::collections::HashMap<String, String> = headers
                .into_iter()
                .filter(|(_, value)| {
                    let trimmed = value.trim();
                    !trimmed.is_empty()
                        && trimmed != "<redacted>"
                        && !trimmed.contains("<redacted>")
                })
                .collect();
            if !live.is_empty() {
                let name = ensure_env_name(
                    &mut n.headers_env,
                    auto_name(organization, &["N", &identity, "WEBHOOK_HEADERS"]),
                );
                if let Ok(value) = serde_json::to_string(&live) {
                    push_write(writes, name, value);
                }
            }
        }
        NotifierConfig::Express(n) => {
            if let Some(value) = take_inline(&mut n.access_token) {
                let name = ensure_env_name(
                    &mut n.access_token_env,
                    auto_name(organization, &["N", &identity, "EXPRESS_TOKEN"]),
                );
                push_write(writes, name, value);
            }
        }
        NotifierConfig::Novu(n) => {
            if let Some(value) = take_inline(&mut n.api_key) {
                let name = ensure_env_name(
                    &mut n.api_key_env,
                    auto_name(organization, &["N", &identity, "NOVU_KEY"]),
                );
                push_write(writes, name, value);
            }
        }
        NotifierConfig::Slack(n) => {
            if let Some(value) = take_inline(&mut n.webhook_url) {
                let name = ensure_env_name(
                    &mut n.webhook_url_env,
                    auto_name(organization, &["N", &identity, "SLACK_WEBHOOK"]),
                );
                push_write(writes, name, value);
            }
            if let Some(value) = take_inline(&mut n.bot_token) {
                let name = ensure_env_name(
                    &mut n.bot_token_env,
                    auto_name(organization, &["N", &identity, "SLACK_BOT"]),
                );
                push_write(writes, name, value);
            }
        }
        NotifierConfig::Telegram(n) => {
            if let Some(value) = take_inline(&mut n.bot_token) {
                let name = ensure_env_name(
                    &mut n.bot_token_env,
                    auto_name(organization, &["N", &identity, "TELEGRAM_BOT"]),
                );
                push_write(writes, name, value);
            }
        }
        NotifierConfig::Smtp(n) => {
            if let Some(value) = take_inline(&mut n.password) {
                let name = ensure_env_name(
                    &mut n.password_env,
                    auto_name(organization, &["N", &identity, "SMTP_PASSWORD"]),
                );
                push_write(writes, name, value);
            }
        }
        NotifierConfig::Rabbitmq(n) => {
            if let Some(value) = take_inline(&mut n.url) {
                let name = ensure_env_name(
                    &mut n.url_env,
                    auto_name(organization, &["N", &identity, "RABBITMQ_URL"]),
                );
                push_write(writes, name, value);
            }
        }
        NotifierConfig::Nats(n) => {
            if let Some(value) = take_inline(&mut n.url) {
                let name = ensure_env_name(
                    &mut n.url_env,
                    auto_name(organization, &["N", &identity, "NATS_URL"]),
                );
                push_write(writes, name, value);
            }
        }
        NotifierConfig::Kafka(_) => {}
    }
}

#[derive(Serialize)]
struct DesiredWire<'a> {
    #[serde(skip_serializing_if = "Option::is_none")]
    defaults: Option<&'a crate::config::Defaults>,
    #[serde(skip_serializing_if = "Vec::is_empty")]
    notifiers: &'a Vec<NotifierConfig>,
    #[serde(skip_serializing_if = "Vec::is_empty")]
    teams: &'a Vec<crate::config::TeamConfig>,
    #[serde(skip_serializing_if = "std::collections::BTreeMap::is_empty")]
    presets: &'a std::collections::BTreeMap<String, crate::config::SourcePreset>,
    #[serde(skip_serializing_if = "Vec::is_empty")]
    sources: &'a Vec<SourceConfig>,
}

fn serialize_desired_only(format: DesiredFormat, config: &Config) -> Result<String, StoreError> {
    let wire = DesiredWire {
        defaults: (config.defaults != crate::config::Defaults::default())
            .then_some(&config.defaults),
        notifiers: &config.notifiers,
        teams: &config.teams,
        presets: &config.presets,
        sources: &config.sources,
    };
    match format {
        DesiredFormat::Yaml => serde_yaml::to_string(&wire)
            .map_err(|err| StoreError::Other(format!("serializing desired YAML: {err}"))),
        DesiredFormat::Toml => toml::to_string_pretty(&wire)
            .map_err(|err| StoreError::Other(format!("serializing desired TOML: {err}"))),
    }
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn normalize_should_move_inline_secrets_to_env_refs() {
        let raw = r#"
notifiers:
  - type: telegram
    bot_token: secret-bot
    chat_id: "-100"
  - type: smtp
    host: smtp.example.com
    from: a@b.c
    to: ["c@d.e"]
    password: smtp-pass
sources:
  - type: github
    repo: org/app
    token: ghp_test
"#;
        let (content, writes) = normalize_document_for_storage(raw, None).expect("normalize");
        assert!(!content.contains("secret-bot"));
        assert!(!content.contains("smtp-pass"));
        assert!(!content.contains("ghp_test"));
        assert_eq!(writes.len(), 3);
        assert!(writes.iter().any(|w| w.value == "secret-bot"));
        assert!(writes.iter().any(|w| w.value == "smtp-pass"));
        assert!(writes.iter().any(|w| w.value == "ghp_test"));

        let config = parse_desired_document(&content).expect("parse");
        match &config.notifiers[0] {
            NotifierConfig::Telegram(n) => {
                assert!(n.bot_token.is_empty());
                assert!(n
                    .bot_token_env
                    .as_deref()
                    .is_some_and(|name| !name.is_empty()));
            }
            other => panic!("unexpected {other:?}"),
        }
        match &config.sources[0] {
            SourceConfig::Github(c) => {
                assert!(c.token.is_none());
                assert!(c.token_env.is_some());
            }
            other => panic!("unexpected {other:?}"),
        }
    }

    #[test]
    fn normalize_should_pack_apprise_urls_and_webhook_headers() {
        let raw = r#"
[[notifiers]]
type = "apprise"
urls = ["tgram://bot/chat"]

[[notifiers]]
type = "webhook"
url = "https://hooks.example/x"
headers = { Authorization = "Bearer tok" }
"#;
        let (content, writes) =
            normalize_document_for_storage(raw, Some("platform")).expect("normalize");
        assert!(!content.contains("tgram://bot/chat"));
        assert!(!content.contains("Bearer tok"));
        assert!(writes.iter().any(|w| w.value.contains("tgram")));
        assert!(writes.iter().any(|w| w.value.contains("Bearer tok")));
        let config = parse_desired_document(&content).expect("parse");
        match &config.notifiers[0] {
            NotifierConfig::Apprise(n) => {
                assert!(n.urls.is_empty());
                assert!(n.urls_env.is_some());
            }
            other => panic!("unexpected {other:?}"),
        }
    }

    #[test]
    fn rotating_inline_secret_should_keep_same_ledger_body() {
        let first = r#"
[[notifiers]]
type = "telegram"
chat_id = "-100"
bot_token = "secret-A"
"#;
        let (content_a, writes_a) =
            normalize_document_for_storage(first, None).expect("normalize A");
        assert_eq!(writes_a.len(), 1);
        assert_eq!(writes_a[0].value, "secret-A");

        let env_name = writes_a[0].name.clone();
        let second = format!(
            r#"
[[notifiers]]
type = "telegram"
chat_id = "-100"
bot_token = "secret-B"
bot_token_env = "{env_name}"
"#
        );
        let (content_b, writes_b) =
            normalize_document_for_storage(&second, None).expect("normalize B");
        assert_eq!(writes_b.len(), 1);
        assert_eq!(writes_b[0].value, "secret-B");
        assert_eq!(writes_b[0].name, env_name);
        assert_eq!(
            content_a, content_b,
            "refs-only ledger body must be stable across secret rotation"
        );
    }

    #[test]
    fn normalize_should_drop_partial_redaction_markers() {
        let raw = r#"
[[notifiers]]
type = "nats"
subject = "releases"
url = "nats://<redacted>@nats.internal:4222"
"#;
        let (content, writes) = normalize_document_for_storage(raw, None).expect("normalize");
        assert!(
            writes.is_empty(),
            "must not vault a redaction marker: {writes:?}"
        );
        assert!(!content.contains("<redacted>"));
    }

    #[test]
    fn normalize_should_prefer_stable_notifier_identity_over_index() {
        let raw = r#"
[[notifiers]]
type = "telegram"
name = "platform-alerts"
tags = ["platform"]
chat_id = "-100111"
bot_token = "secret-bot"
"#;
        let (_content, writes) = normalize_document_for_storage(raw, None).expect("normalize");
        assert_eq!(writes.len(), 1);
        assert!(
            writes[0].name.contains("PLATFORM_ALERTS"),
            "expected name-based vault key, got {}",
            writes[0].name
        );
        assert!(
            !writes[0].name.contains("_N_0_"),
            "must not key only by list index: {}",
            writes[0].name
        );
    }

    #[test]
    fn collect_refs_and_stale_should_scope_ui_managed_names() {
        let previous: Config = toml::from_str(
            r#"
 [[notifiers]]
 type = "telegram"
 chat_id = "-100"
 bot_token_env = "XRELEASE_UI_N_0_TELEGRAM_BOT"

 [[notifiers]]
 type = "smtp"
 host = "smtp.example.com"
 from = "a@b.c"
 to = ["c@d.e"]
 password_env = "MY_CUSTOM_SMTP"
 "#,
        )
        .expect("parse");
        let next: Config = toml::from_str(
            r#"
 [[notifiers]]
 type = "smtp"
 host = "smtp.example.com"
 from = "a@b.c"
 to = ["c@d.e"]
 password_env = "MY_CUSTOM_SMTP"
 "#,
        )
        .expect("parse");
        let prev_refs = collect_secret_env_refs(&previous);
        let next_refs = collect_secret_env_refs(&next);
        let stale = stale_ui_managed_secrets(&prev_refs, &next_refs, None);
        assert_eq!(stale, vec!["XRELEASE_UI_N_0_TELEGRAM_BOT".to_owned()]);
        // Custom env names are never auto-pruned (may live only in process env).
        assert!(!stale.iter().any(|name| name == "MY_CUSTOM_SMTP"));
    }

    #[test]
    fn ui_managed_secret_name_should_respect_organization_prefix() {
        assert!(is_ui_managed_secret_name(
            "XRELEASE_UI_PLATFORM_N_0_TELEGRAM_BOT",
            Some("platform")
        ));
        assert!(!is_ui_managed_secret_name(
            "XRELEASE_UI_OTHER_N_0_TELEGRAM_BOT",
            Some("platform")
        ));
        assert!(!is_ui_managed_secret_name(
            "XRELEASE_UI_PLATFORM_N_0_TELEGRAM_BOT",
            None
        ));
        assert!(is_ui_managed_secret_name(
            "XRELEASE_UI_N_0_TELEGRAM_BOT",
            None
        ));
    }
}
