/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Liveness probe (process up)
         * @description Returns 200 while the process is running. Outbox counters are best-effort when PostgreSQL is reachable; dependency readiness belongs on `/ready`.
         */
        get: operations["getHealth"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/ready": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Readiness probe (PostgreSQL + Apprise reachable) */
        get: operations["getReady"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/auth/methods": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Which login methods are available */
        get: operations["getAuthMethods"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/auth/login": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Local username/password login */
        post: operations["postAuthLogin"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/auth/oidc/sync": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Upsert OIDC user and assign role from claims */
        post: operations["postAuthOidcSync"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/auth/me": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Current authenticated principal */
        get: operations["getAuthMe"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/auth/logout": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Revoke the caller's live sessions (bumps session_version) */
        post: operations["logout"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/auth/users": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List application users (local + OIDC)
         * @description Admin-only directory of persisted identities. OIDC rows appear after the first successful `/auth/oidc/sync`.
         */
        get: operations["listAuthUsers"];
        put?: never;
        /**
         * Create a local username/password user
         * @description Admin-only. Requires local auth to be enabled. OIDC users appear via `/auth/oidc/sync` (auto-links matching local email) or admin `POST …/users/{id}/oidc`.
         */
        post: operations["createAuthUser"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/auth/users/{id}/oidc": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Link or unlink an OIDC subject on a local user
         * @description Admin-only. Attaches `oidc_sub` to an existing local (password) user so the same row can sign in via SSO. `auth_source` stays `local`. Pass a blank/null `oidc_sub` to unlink. Auto-link also happens on `/auth/oidc/sync` when emails match.
         */
        post: operations["linkAuthUserOidc"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/metrics": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Prometheus metrics */
        get: operations["getMetrics"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/openapi.json": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** OpenAPI 3 specification (this document) */
        get: operations["getOpenApiSpec"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/status": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Process overview for dashboard UI */
        get: operations["getStatus"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/config": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Effective running config (secrets redacted) */
        get: operations["getConfig"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/config/validate": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Dry-run config apply (no persistence) */
        post: operations["validateConfig"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/config/apply": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Apply desired-state TOML with hot-swap
         * @description Requires `[config_api].api_config = true` and `source = api`. Optional HMAC via `X-Config-Signature: sha256=…` when `XRELEASE_CONFIG_APPLY_SECRET` is set.
         */
        post: operations["applyConfig"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/config/rollback": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Re-apply the previous ledger revision */
        post: operations["rollbackConfig"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/sources": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List configured sources with live runtime state */
        get: operations["listSources"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/sources/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get one source with runtime state */
        get: operations["getSource"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/outbox": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Pending/failed notification outbox */
        get: operations["listOutbox"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/outbox/requeue": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Requeue dead-letter outbox notifications
         * @description Revive rows in `dead` status back to `pending` (same as CLI `xrelease outbox requeue`). Rate-limited with other mutating management routes.
         */
        post: operations["requeueOutbox"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/teams": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Team routing catalogue with per-team source counts */
        get: operations["listTeams"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/notifiers": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List configured notification sinks
         * @description Runtime snapshot of delivery channels (Apprise, SMTP, eXpress, webhooks, …) with index, kind, name, and routing tags.
         */
        get: operations["listNotifiers"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/notifiers/test": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Send a test notification through live sinks
         * @description Force-delivers a synthetic event to one sink (by index) or every configured sink. Bypasses team-tag routing so operators can verify Apprise / SMTP / eXpress / webhook delivery after config changes.
         */
        post: operations["testNotifiers"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/check": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Trigger a one-shot poll of all sources */
        post: operations["triggerCheck"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/check/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Trigger a one-shot poll of one configured source */
        post: operations["triggerCheckSource"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/webhooks/github": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * GitHub release webhook
         * @description Accepts GitHub `release` events with `action=published`. Maps `repository.full_name` to a configured `type=github` source.
         */
        post: operations["webhookGithub"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/webhooks/gitlab": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** GitLab release webhook */
        post: operations["webhookGitlab"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/webhooks/gitea": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Gitea / Forgejo release webhook
         * @description GitHub-compatible release payload. Authenticated via `X-Webhook-Secret` or `Authorization: Bearer`.
         */
        post: operations["webhookGitea"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/webhooks/bitbucket": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Bitbucket tag push webhook
         * @description Accepts Bitbucket `repo:push` events with a new tag in `push.changes`. Maps `repository.full_name` to a configured `type=bitbucket` source. Authenticated via `X-Hub-Signature` (HMAC-SHA256 hex) when `[api].webhook_secret` is set.
         */
        post: operations["webhookBitbucket"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/webhooks/docker": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Docker Hub registry push webhook
         * @description Docker Hub automated build / push payload (`push_data.tag`, `repository.repo_name`). Matches `docker`, `ghcr`, or `quay` sources by image path.
         */
        post: operations["webhookDocker"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/webhooks/generic": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Generic release push webhook
         * @description Custom integrations — specify `source_id` and `tag` explicitly.
         */
        post: operations["webhookGeneric"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/reload": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Re-read the app config file and hot-swap it
         * @description File-mode counterpart of /api/v1/config/apply: takes no body and re-reads the configured app config file (--app / XRELEASE_APP_CONFIG), validates it, and hot-swaps sources, notifiers, and teams. Returns 409 when a config ledger revision is authoritative (use /api/v1/config/apply instead) and 400 when no app config file is configured. Also triggered by SIGHUP.
         */
        post: operations["reloadConfig"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/config/revisions": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Config apply/reject audit history (paginated)
         * @description Newest-first page of the config revision ledger. Returns metadata only — revision bodies are deliberately omitted so this endpoint cannot bypass the secret redaction applied by GET /api/v1/config. Includes rejected apply attempts and their errors. `applied_by` is the server-verified principal (`api_key`, `oidc:<sub>`), optionally annotated with a client-supplied X-Config-Applied-By label in parentheses.
         */
        get: operations["getConfigRevisions"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/config/schema": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * What the desired-state config accepts (for UI controls)
         * @description Machine-readable option lists so a UI can render selects, a sink picker, a team-tag multi-select and a schedule widget instead of a raw config text box. Deployment/build specific: `sink_kinds[].available` (cargo features), `team_tags` / `preset_names` (running config), and `config_authority` (`[config_api].source`). `readonly_sections` are bootstrap-only and rejected in any pushed document. `template_placeholders` documents the notifier Mustache dialect.
         */
        get: operations["getConfigSchema"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/organizations": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Organization catalogue ([[organizations]] in bootstrap.toml) */
        get: operations["listOrganizations"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/organizations/{id}/config": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** One organization's desired document from its authority (redacted) */
        get: operations["getOrganizationConfig"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/organizations/{id}/config/revisions": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** This organization's ledger stream (metadata only) */
        get: operations["listOrganizationRevisions"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/organizations/{id}/config/validate": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Dry-run one organization's candidate document against the composed runtime */
        post: operations["validateOrganizationConfig"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/organizations/{id}/config/apply": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Replace one organization's desired document (hot-swap + org ledger stream)
         * @description Requires [config_api].api_config = true and source = "api". If-Match compares against this organization's current authority sha (ETag of GET./config).
         */
        post: operations["applyOrganizationConfig"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/organizations/{id}/config/rollback": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Re-apply the previous applied revision of this organization's stream */
        post: operations["rollbackOrganizationConfig"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        HealthResponse: {
            /** @enum {string} */
            status: "ok" | "error";
            sources: number;
            outbox_pending: number;
            outbox_dead: number;
            /**
             * Format: int64
             * @description Seconds since process start
             */
            uptime_secs?: number;
        };
        ReadyResponse: {
            /** @enum {string} */
            status: "ready" | "not_ready";
            database_ok: boolean;
            /** @description Configured sinks report healthy. Apprise uses a live HTTP probe; other sinks (SMTP, webhook, brokers) are presence-based so transient blips do not flap readiness — delivery failures appear in the outbox metrics. */
            notifiers_ok: boolean;
            outbox_pending: number;
            outbox_dead: number;
        };
        ErrorResponse: {
            error: string;
        };
        SourceSummary: {
            /** @example github:tokio-rs/tokio */
            id: string;
            /**
             * @description Provider kind: github, codeberg, gitea, gitlab, bitbucket, docker, ghcr, quay, ecr, feed, pypi, npm, yarn, cargo, maven, nuget, hex, rubygems, packagist, cpan, artifacthub
             * @example github
             */
            kind: string;
            kind_label: string;
            display_name: string;
            interval_secs: number;
            jitter_secs: number;
            /** @description Team routing tag (matches notifier tags / [[teams]].tag). */
            routing_tag: string | null;
            /**
             * @description Cron expression (UTC) gating notification delivery; null = deliver immediately
             * @example 0 9 * * MON-FRI
             */
            notify_schedule: string | null;
            /** @description Owning organization id when multi-org; null in legacy single-document mode. */
            organization_id?: string | null;
        };
        SourceMetricsView: {
            /** Format: int64 */
            polls: number;
            /** Format: int64 */
            polls_not_modified: number;
            /** Format: int64 */
            poll_errors: number;
            /** Format: int64 */
            notifications: number;
        };
        SeenReleaseView: {
            tag: string;
            published_at?: string | null;
            /** @description Canonical upstream release page (stored at sync time or derived from provider template) */
            url?: string | null;
            first_seen_at: string;
        };
        SourceDetail: components["schemas"]["SourceSummary"] & {
            initialized: boolean;
            last_polled_at: string | null;
            /** Format: int64 */
            seen_count: number;
            latest_release_tag: string | null;
            /** @description Upstream catalog page (repo, package index, feed URL) */
            source_page_url?: string | null;
            seen_releases: components["schemas"]["SeenReleaseView"][];
            /** Format: int64 */
            polls: number;
            /** Format: int64 */
            polls_not_modified: number;
            /** Format: int64 */
            poll_errors: number;
            /** Format: int64 */
            notifications: number;
        };
        MetricsSnapshot: {
            /** Format: int64 */
            polls_total: number;
            /** Format: int64 */
            polls_not_modified: number;
            /** Format: int64 */
            poll_errors: number;
            /** Format: int64 */
            notifications_total: number;
            /** Format: int64 */
            webhooks_accepted: number;
            /** Format: int64 */
            webhooks_ignored: number;
            /** Format: int64 */
            webhooks_duplicates: number;
            /** Format: int64 */
            webhooks_errors: number;
            /** Format: int64 */
            config_apply_total: number;
            /** Format: int64 */
            config_apply_rejected_total: number;
            /** Format: int64 */
            notify_breaker_skips: number;
            /** Format: int64 */
            outbox_enqueued_total: number;
            /** Format: int64 */
            outbox_delivery_failures_total: number;
            /** Format: int64 */
            outbox_dead_lettered_total: number;
            /** Format: int64 */
            outbox_requeued_total: number;
            /** Format: int64 */
            http_rate_limited_total: number;
            /** Format: int64 */
            prune_deleted_total: number;
        };
        StatusResponse: {
            version: string;
            /** Format: int64 */
            uptime_secs: number;
            database_ok: boolean;
            sources_configured: number;
            outbox_pending: number;
            outbox_dead: number;
            metrics: components["schemas"]["MetricsSnapshot"];
            config_apply: components["schemas"]["ConfigApplyStatus"];
            /** @description Pending/failed rows held until deliver_after (notify_schedule). */
            outbox_deferred: number;
            breakers: components["schemas"]["BreakerOpenView"][];
        };
        ConfigApplyStatus: {
            /** @description Whether POST apply/rollback routes are mounted ([config_api].api_config). */
            api_config_enabled: boolean;
            /** @description Whether the dashboard form editor is on (ui_config + api_config + source=api). */
            ui_config_enabled: boolean;
            /**
             * @description Declared desired-state authority ([config_api].source).
             * @enum {string}
             */
            config_source: "local" | "api";
            hmac_configured: boolean;
            /** @enum {string} */
            desired_source: "ledger" | "app_file" | "empty";
            bootstrap_path: string;
            /** Format: int64 */
            revision?: number | null;
            content_sha256?: string | null;
            revision_label?: string | null;
            /** Format: date-time */
            applied_at?: string | null;
            /** Format: int64 */
            last_rejected_revision?: number | null;
            last_rejected_error?: string | null;
        };
        ConfigView: {
            /** @description Redacted effective TOML (bootstrap + desired) */
            content: string;
            /** @description Redacted desired-state document only */
            desired_content?: string | null;
            /** @enum {string} */
            desired_source: "ledger" | "app_file" | "empty";
            content_sha256?: string | null;
            /** Format: int64 */
            revision?: number | null;
            revision_label?: string | null;
            applied_at?: string | null;
            bootstrap_path: string;
            /** @description Whether POST apply/rollback routes are mounted ([config_api].api_config). */
            api_config_enabled: boolean;
            bootstrap_sections: string[];
            /** @description Whether the dashboard should offer a config editor ([config_api].ui_config, which also requires api_config and source=api). */
            ui_config_enabled?: boolean;
            /**
             * @description Declared authority for desired state ([config_api].source). `local` refuses pushed config with 409.
             * @enum {string}
             */
            config_source?: "local" | "api";
        };
        ConfigValidateResponse: {
            valid: boolean;
            content_sha256: string;
            report: Record<string, never>;
        };
        ConfigApplyResponse: {
            applied: boolean;
            content_sha256: string;
            /** Format: int64 */
            revision: number;
            sources_added?: string[];
            sources_removed?: string[];
            sources_changed?: string[];
            warnings?: string[];
        };
        OutboxEntry: {
            /** Format: int64 */
            id: number;
            source_id: string;
            identity: string;
            /** @enum {string} */
            status: "pending" | "failed" | "dead";
            attempts: number;
            last_error: string | null;
            created_at: string;
            title: string;
            url: string | null;
            /** @description Team routing tag carried on the event. */
            routing_tag: string | null;
            /**
             * Format: date-time
             * @description Delivery is held until this moment (notify_schedule); null = deliver as soon as possible
             */
            deliver_after: string | null;
            /** @description Derived from namespaced source_id (org::…). */
            organization_id?: string | null;
        };
        OutboxListResponse: {
            entries: components["schemas"]["OutboxEntry"][];
        };
        OutboxRequeueResponse: {
            /** @description Number of dead outbox rows reset to pending */
            requeued: number;
        };
        TeamView: {
            /** @description Routing tag shared by sources (`routing_tag`) and notifiers (`tags`) */
            tag: string;
            /** @description Human-readable label from [[teams]].name */
            name?: string | null;
            /** @description Number of configured sources routing to this tag */
            source_count: number;
        };
        TeamListResponse: {
            teams: components["schemas"]["TeamView"][];
        };
        CheckRequest: {
            /**
             * @description Fetch only — do not persist or notify
             * @default false
             */
            dry_run: boolean;
        };
        CheckResponse: {
            notifications_sent: number;
            sources_checked: number;
        };
        NotifierView: {
            /** @description Stable index into the running CompositeNotifier */
            index: number;
            /** @description Backend kind (`apprise`, `smtp`, `express`, `webhook`, …) */
            kind: string;
            /** @description Config `name` when set, otherwise the kind */
            name: string;
            /** @description Routing tags (empty = wildcard / all events) */
            tags: string[];
        };
        NotifierListResponse: {
            notifiers: components["schemas"]["NotifierView"][];
        };
        NotifierTestRequest: {
            /** @description When set, only this sink is probed; omit to test every sink */
            index?: number | null;
            /** @description Optional override for the synthetic event title */
            title?: string | null;
            /** @description Optional override for the synthetic event body */
            body?: string | null;
        };
        NotifierTestResult: {
            index: number;
            kind: string;
            name: string;
            ok: boolean;
            /** @description Present when `ok` is false */
            error?: string | null;
        };
        NotifierTestResponse: {
            results: components["schemas"]["NotifierTestResult"][];
        };
        WebhookResponse: {
            accepted: boolean;
            source_id: string | null;
            tag: string | null;
            notifications_sent: number;
            message: string;
        };
        GithubWebhook: {
            /** @example published */
            action?: string;
            release?: components["schemas"]["GithubRelease"];
            repository?: {
                /** @example owner/repo */
                full_name?: string;
            };
        };
        GithubRelease: {
            tag_name?: string;
            /** Format: uri */
            html_url?: string;
            body?: string;
            prerelease?: boolean;
            draft?: boolean;
            /** Format: date-time */
            published_at?: string;
        };
        GitlabWebhook: {
            /** @example release */
            object_kind?: string;
            tag?: string;
            name?: string;
            description?: string;
            /** Format: uri */
            url?: string;
            /** Format: date-time */
            released_at?: string;
            project?: {
                path_with_namespace?: string;
                name?: string;
            };
        };
        DockerPushWebhook: {
            push_data?: {
                /** @example 1.2.3 */
                tag?: string;
            };
            repository?: {
                /** @example library/nginx */
                repo_name?: string;
                name?: string;
            };
        };
        BitbucketPushWebhook: {
            push?: {
                changes?: {
                    new?: {
                        /** @example tag */
                        type?: string;
                        /** @example 1.2.3 */
                        name?: string;
                        target?: {
                            links?: {
                                html?: {
                                    /** Format: uri */
                                    href?: string;
                                };
                            };
                        };
                    };
                }[];
            };
            repository?: {
                /** @example workspace/repo */
                full_name?: string;
            };
        };
        GenericWebhook: {
            /** @example pypi:requests */
            source_id: string;
            /** @example 2.32.0 */
            tag: string;
            /** Format: uri */
            url?: string;
            body?: string;
            /** @default false */
            prerelease: boolean;
        };
        ConfigReloadResponse: {
            applied: boolean;
            content_sha256: string;
            source_path: string;
            sources_added?: string[];
            sources_removed?: string[];
            sources_changed?: string[];
            warnings?: string[];
        };
        /** @description One ledger row without its config body. */
        ConfigRevisionSummary: {
            /** Format: int64 */
            id: number;
            content_sha256: string;
            revision_label?: string | null;
            /** Format: date-time */
            applied_at: string;
            /** @description Server-verified principal, e.g. `api_key` or `oidc:<sub>` */
            applied_by?: string | null;
            source_addr?: string | null;
            /** @enum {string} */
            status: "applied" | "rejected";
            error?: string | null;
            /** @description Ledger stream: absent/null = legacy single-document stream, else the [[organizations]] id. */
            organization_id?: string | null;
        };
        ConfigRevisionsResponse: {
            revisions: components["schemas"]["ConfigRevisionSummary"][];
            /** Format: int64 */
            total: number;
            /** Format: int64 */
            limit: number;
            /** Format: int64 */
            offset: number;
        };
        ConfigSchema: {
            source_kinds: {
                value: string;
                label: string;
            }[];
            sink_kinds: {
                value: string;
                label: string;
                /** @description False when the sink needs a cargo feature this build lacks */
                available: boolean;
                requires_feature?: string | null;
            }[];
            smtp_tls_modes?: {
                value: string;
                label: string;
            }[];
            webhook_methods?: {
                value: string;
                label: string;
            }[];
            team_tags: string[];
            /** @description Effective preset names (built-ins + user `presets`) */
            preset_names: string[];
            /** @description Built-in source presets with filter fields (SSOT for UI templates) */
            builtin_presets: {
                name: string;
                description: string;
                include_prerelease?: boolean | null;
                prerelease_tags?: string[] | null;
                exclude_updated?: boolean | null;
                pattern?: string | null;
                exclude_pattern?: string | null;
            }[];
            /** @description Shared fields accepted on every source (and inside `presets`) */
            source_common_fields: string[];
            /** @description Mustache-style `{{name}}` placeholders for notifier body/subject/key templates */
            template_placeholders: string[];
            notify_schedule?: Record<string, never>;
            limits?: Record<string, never>;
            readonly_sections: string[];
            /** @description Which store owns desired state (`[config_api].source`) and whether pushes are accepted */
            config_authority: {
                /** @enum {string} */
                source: "local" | "api";
                routes_enabled: boolean;
                accepts_pushed_config: boolean;
            };
        };
        OrganizationView: {
            /** @description Catalogue slug ([[organizations]].id). */
            id: string;
            /** @description Display name (falls back to id). */
            name: string;
            /** @description Watches currently running for this organization. */
            source_count: number;
        };
        OrganizationListResponse: {
            organizations: components["schemas"]["OrganizationView"][];
            /**
             * @description Desired-state authority declared in [config_api].
             * @enum {string}
             */
            config_source: "local" | "api";
            api_config_enabled: boolean;
            /** @description Whether the dashboard form editor is on (ui_config + api_config + source=api). */
            ui_config_enabled?: boolean;
        };
        OrganizationConfigView: {
            organization: string;
            name: string;
            /**
             * @description Authority the document was read from.
             * @enum {string}
             */
            desired_source: "ledger" | "app_file" | "empty";
            /** @description SHA-256 of the raw desired document; also sent as the ETag header for If-Match. */
            content_sha256: string;
            /** @description Redacted desired document. */
            desired_content?: string | null;
            /** @description [[organizations]].app path (seed / GitOps authority). Null when omitted for API/UI-authored orgs. */
            app_path?: string | null;
            /** @enum {string} */
            config_source?: "local" | "api";
            accepts_pushed_config?: boolean;
            /** @description Whether POST apply/rollback routes are mounted ([config_api].api_config). */
            api_config_enabled?: boolean;
            /** @description Whether the dashboard should offer the form editor ([config_api].ui_config). */
            ui_config_enabled?: boolean;
        };
        OrganizationRevisionsResponse: {
            organization: string;
            revisions: components["schemas"]["ConfigRevisionSummary"][];
            total: number;
            limit: number;
            offset: number;
        };
        /** @enum {string} */
        AppRole: "admin" | "operator" | "viewer";
        AuthLoginRequest: {
            username: string;
            /** Format: password */
            password: string;
        };
        AuthUserView: {
            /** Format: int64 */
            id: number;
            username?: string | null;
            email?: string | null;
            display_name?: string | null;
            role: components["schemas"]["AppRole"];
            /**
             * @description `local` (password) or `oidc` (created/synced from IdP).
             * @enum {string}
             */
            auth_source: "local" | "oidc";
            /** @description OIDC subject (`sub`) when the user is linked to an IdP identity. Omitted when unset. */
            oidc_sub?: string | null;
            /** Format: date-time */
            created_at: string;
            /**
             * Format: date-time
             * @description Last successful login. Omitted when the user has never signed in.
             */
            last_login_at?: string | null;
            /** @description Per-organization role grants from OIDC scoped aliases (e.g. xrelease-admin:platform). Omitted when empty. */
            organization_roles?: {
                [key: string]: components["schemas"]["AppRole"];
            };
        };
        AuthUserListResponse: {
            users: components["schemas"]["AuthUserView"][];
        };
        AuthCreateUserRequest: {
            username: string;
            /** Format: password */
            password: string;
            role: components["schemas"]["AppRole"];
            email?: string | null;
            display_name?: string | null;
        };
        AuthLinkOidcRequest: {
            /** @description IdP subject to attach. Null or blank unlinks SSO from the local user. */
            oidc_sub?: string | null;
        };
        AuthLoginResponse: {
            access_token: string;
            token_type: string;
            /** Format: int64 */
            expires_in: number;
            role: components["schemas"]["AppRole"];
            user: components["schemas"]["AuthUserView"];
        };
        AuthMethodsResponse: {
            local: boolean;
            oidc: boolean;
            api_key: boolean;
        };
        AuthMeResponse: {
            method: string;
            /** @description Instance-wide role. Api-key principals are always admin. */
            role?: components["schemas"]["AppRole"] | null;
            /** @description Per-organization grants from OIDC scoped aliases (admin:platform). Empty for local and api-key. */
            organization_roles: {
                [key: string]: components["schemas"]["AppRole"];
            };
            user?: components["schemas"]["AuthUserView"] | null;
        };
        BreakerOpenView: {
            /** @description Backend kind (apprise, webhook, …) */
            kind: string;
            /** @description Operator-facing sink label */
            label: string;
            /** @description True when the breaker is rejecting calls */
            open: boolean;
        };
    };
    responses: {
        /** @description Authentication failed */
        Unauthorized: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["ErrorResponse"];
            };
        };
        /** @description Invalid payload */
        BadRequest: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["ErrorResponse"];
            };
        };
        /** @description Authenticated but insufficient role */
        Forbidden: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["ErrorResponse"];
            };
        };
        /** @description Request conflicts with current state */
        Conflict: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["ErrorResponse"];
            };
        };
        /** @description No matching configured source */
        NotFound: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["ErrorResponse"];
            };
        };
        /** @description Internal error */
        InternalError: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["ErrorResponse"];
            };
        };
    };
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    getHealth: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Process is up */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HealthResponse"];
                };
            };
        };
    };
    getReady: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description All dependencies ready */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ReadyResponse"];
                };
            };
            /** @description Database or Apprise unreachable */
            503: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ReadyResponse"];
                };
            };
        };
    };
    getAuthMethods: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Local / OIDC / API key flags */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AuthMethodsResponse"];
                };
            };
        };
    };
    postAuthLogin: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["AuthLoginRequest"];
            };
        };
        responses: {
            /** @description Session JWT */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AuthLoginResponse"];
                };
            };
            401: components["responses"]["Unauthorized"];
        };
    };
    postAuthOidcSync: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Persisted user profile */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AuthUserView"];
                };
            };
            401: components["responses"]["Unauthorized"];
        };
    };
    getAuthMe: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Principal + optional user */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AuthMeResponse"];
                };
            };
            401: components["responses"]["Unauthorized"];
        };
    };
    logout: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description revoked (true for a local session, false otherwise) */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        revoked?: boolean;
                    };
                };
            };
            /** @description Missing/invalid or revoked bearer */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    listAuthUsers: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description User directory */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AuthUserListResponse"];
                };
            };
            401: components["responses"]["Unauthorized"];
            403: components["responses"]["Forbidden"];
        };
    };
    createAuthUser: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["AuthCreateUserRequest"];
            };
        };
        responses: {
            /** @description Created user */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AuthUserView"];
                };
            };
            400: components["responses"]["BadRequest"];
            401: components["responses"]["Unauthorized"];
            403: components["responses"]["Forbidden"];
            409: components["responses"]["Conflict"];
        };
    };
    linkAuthUserOidc: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: number;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["AuthLinkOidcRequest"];
            };
        };
        responses: {
            /** @description Updated user */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AuthUserView"];
                };
            };
            400: components["responses"]["BadRequest"];
            401: components["responses"]["Unauthorized"];
            403: components["responses"]["Forbidden"];
            404: components["responses"]["NotFound"];
            409: components["responses"]["Conflict"];
        };
    };
    getMetrics: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Prometheus text exposition format */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "text/plain": string;
                };
            };
        };
    };
    getOpenApiSpec: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OpenAPI JSON document */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": Record<string, never>;
                };
            };
        };
    };
    getStatus: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Uptime, metrics snapshot, outbox depth */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["StatusResponse"];
                };
            };
            401: components["responses"]["Unauthorized"];
        };
    };
    getConfig: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Merged bootstrap + desired state with provenance */
            200: {
                headers: {
                    /** @description SHA-256 of the running desired document; send back as If-Match on apply */
                    ETag?: string;
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ConfigView"];
                };
            };
            401: components["responses"]["Unauthorized"];
        };
    };
    validateConfig: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/toml": string;
            };
        };
        responses: {
            /** @description Validation report */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ConfigValidateResponse"];
                };
            };
            401: components["responses"]["Unauthorized"];
            /** @description Authenticated but the principal's role is insufficient (RBAC). */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    applyConfig: {
        parameters: {
            query?: never;
            header?: {
                /** @description Git commit / pipeline label stored in the ledger */
                "X-Config-Revision"?: string;
                /** @description HMAC-SHA256 of the raw body (`sha256=<hex>`) */
                "X-Config-Signature"?: string;
                /** @description Optimistic concurrency: the ETag read from GET /api/v1/config. Omit for an unconditional apply (CI pushing committed state). `*` requires that some config is already applied. */
                "If-Match"?: string;
            };
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/toml": string;
            };
        };
        responses: {
            /** @description Apply succeeded or was idempotent (same sha) */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ConfigApplyResponse"];
                };
            };
            /** @description Body is not a parseable desired-state document */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            401: components["responses"]["Unauthorized"];
            /** @description Authenticated but the principal's role is insufficient (RBAC). */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Config apply API disabled (`[config_api].api_config = false`) */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description config_api.source = "local": the app file is authoritative, pushes refused */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description If-Match precondition failed — config changed since it was read */
            412: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation failed — previous config keeps running */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    rollbackConfig: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Rollback applied */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ConfigApplyResponse"];
                };
            };
            401: components["responses"]["Unauthorized"];
            /** @description Authenticated but the principal's role is insufficient (RBAC). */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Config apply API disabled */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description No previous applied revision to roll back to, or the instance is local-file authoritative (source = local) */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    listSources: {
        parameters: {
            query?: {
                /** @description Limit results to one organization (namespaced ids/tags). Requires Viewer on that org. */
                organization?: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Config + poll state + per-source metrics */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SourceDetail"][];
                };
            };
            401: components["responses"]["Unauthorized"];
        };
    };
    getSource: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Source detail */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SourceDetail"];
                };
            };
            401: components["responses"]["Unauthorized"];
            404: components["responses"]["NotFound"];
        };
    };
    listOutbox: {
        parameters: {
            query?: {
                limit?: number;
                /** @description Limit results to one organization (namespaced ids/tags). Requires Viewer on that org. */
                organization?: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Outbox entries (no message body) */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["OutboxListResponse"];
                };
            };
            401: components["responses"]["Unauthorized"];
        };
    };
    requeueOutbox: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Number of rows revived */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["OutboxRequeueResponse"];
                };
            };
            401: components["responses"]["Unauthorized"];
            /** @description Authenticated but the principal's role is insufficient (RBAC). */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            500: components["responses"]["InternalError"];
        };
    };
    listTeams: {
        parameters: {
            query?: {
                /** @description Limit results to one organization (namespaced ids/tags). Requires Viewer on that org. */
                organization?: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Configured teams (`[[teams]]`) merged with source counts */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TeamListResponse"];
                };
            };
            401: components["responses"]["Unauthorized"];
        };
    };
    listNotifiers: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Configured sinks */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["NotifierListResponse"];
                };
            };
            401: components["responses"]["Unauthorized"];
        };
    };
    testNotifiers: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: {
            content: {
                "application/json": components["schemas"]["NotifierTestRequest"];
            };
        };
        responses: {
            /** @description Per-sink delivery results */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["NotifierTestResponse"];
                };
            };
            401: components["responses"]["Unauthorized"];
            /** @description Authenticated but the principal's role is insufficient (RBAC). */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            404: components["responses"]["NotFound"];
            500: components["responses"]["InternalError"];
        };
    };
    triggerCheck: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: {
            content: {
                "application/json": components["schemas"]["CheckRequest"];
            };
        };
        responses: {
            /** @description Poll completed */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CheckResponse"];
                };
            };
            401: components["responses"]["Unauthorized"];
            /** @description Authenticated but the principal's role is insufficient (RBAC). */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            500: components["responses"]["InternalError"];
        };
    };
    triggerCheckSource: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Configured source id (e.g. `github:org/repo`) */
                id: string;
            };
            cookie?: never;
        };
        requestBody?: {
            content: {
                "application/json": components["schemas"]["CheckRequest"];
            };
        };
        responses: {
            /** @description Poll completed */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CheckResponse"];
                };
            };
            401: components["responses"]["Unauthorized"];
            /** @description Authenticated but the principal's role is insufficient (RBAC). */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            404: components["responses"]["NotFound"];
            500: components["responses"]["InternalError"];
        };
    };
    webhookGithub: {
        parameters: {
            query?: never;
            header?: {
                /** @description HMAC SHA-256 signature when `[api].webhook_secret` is set */
                "X-Hub-Signature-256"?: string;
            };
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["GithubWebhook"];
            };
        };
        responses: {
            /** @description Webhook processed */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["WebhookResponse"];
                };
            };
            400: components["responses"]["BadRequest"];
            401: components["responses"]["Unauthorized"];
            404: components["responses"]["NotFound"];
        };
    };
    webhookGitlab: {
        parameters: {
            query?: never;
            header?: {
                "X-Gitlab-Token"?: string;
            };
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["GitlabWebhook"];
            };
        };
        responses: {
            /** @description Webhook processed */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["WebhookResponse"];
                };
            };
            400: components["responses"]["BadRequest"];
            401: components["responses"]["Unauthorized"];
            404: components["responses"]["NotFound"];
        };
    };
    webhookGitea: {
        parameters: {
            query?: never;
            header?: {
                "X-Webhook-Secret"?: string;
            };
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["GithubWebhook"];
            };
        };
        responses: {
            /** @description Webhook processed */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["WebhookResponse"];
                };
            };
            401: components["responses"]["Unauthorized"];
            404: components["responses"]["NotFound"];
        };
    };
    webhookBitbucket: {
        parameters: {
            query?: never;
            header?: {
                /** @description Must be `repo:push` for tag events */
                "X-Event-Key"?: string;
                /** @description HMAC SHA-256 hex digest of the raw body */
                "X-Hub-Signature"?: string;
                /** @description Idempotency key for duplicate delivery suppression */
                "X-Request-UUID"?: string;
            };
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["BitbucketPushWebhook"];
            };
        };
        responses: {
            /** @description Webhook processed */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["WebhookResponse"];
                };
            };
            400: components["responses"]["BadRequest"];
            401: components["responses"]["Unauthorized"];
            404: components["responses"]["NotFound"];
        };
    };
    webhookDocker: {
        parameters: {
            query?: never;
            header?: {
                "X-Webhook-Secret"?: string;
                "Idempotency-Key"?: string;
            };
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["DockerPushWebhook"];
            };
        };
        responses: {
            /** @description Webhook processed */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["WebhookResponse"];
                };
            };
            401: components["responses"]["Unauthorized"];
            404: components["responses"]["NotFound"];
        };
    };
    webhookGeneric: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["GenericWebhook"];
            };
        };
        responses: {
            /** @description Webhook processed */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["WebhookResponse"];
                };
            };
            401: components["responses"]["Unauthorized"];
            404: components["responses"]["NotFound"];
        };
    };
    reloadConfig: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Reload evaluated (applied=false when unchanged) */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ConfigReloadResponse"];
                };
            };
            /** @description No app config file configured */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Missing or invalid credentials */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Authenticated but the principal's role is insufficient (RBAC). */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Config ledger is authoritative */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Config file failed validation */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    getConfigRevisions: {
        parameters: {
            query?: {
                /** @description Page size (clamped to 1.200) */
                limit?: number;
                /** @description Rows to skip (newest-first ordering) */
                offset?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Revision history page */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ConfigRevisionsResponse"];
                };
            };
            401: components["responses"]["Unauthorized"];
        };
    };
    getConfigSchema: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Config schema for editors */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ConfigSchema"];
                };
            };
            401: components["responses"]["Unauthorized"];
        };
    };
    listOrganizations: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Catalogue with live per-org source counts */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["OrganizationListResponse"];
                };
            };
            /** @description Missing/invalid bearer token */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    getOrganizationConfig: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Organization id ([[organizations]].id). */
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Desired document; ETag header carries content_sha256 for If-Match */
            200: {
                headers: {
                    /** @description Quoted content_sha256 of the raw document. */
                    ETag?: string;
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["OrganizationConfigView"];
                };
            };
            /** @description Unknown organization (or single-document instance) */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    listOrganizationRevisions: {
        parameters: {
            query?: {
                limit?: number;
                offset?: number;
            };
            header?: never;
            path: {
                /** @description Organization id ([[organizations]].id). */
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Page of this org's apply/reject history */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["OrganizationRevisionsResponse"];
                };
            };
            /** @description Unknown organization */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    validateOrganizationConfig: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Organization id ([[organizations]].id). */
                id: string;
            };
            cookie?: never;
        };
        /** @description Complete desired-state document for this organization (YAML or TOML). */
        requestBody: {
            content: {
                "application/yaml": string;
                "application/toml": string;
            };
        };
        responses: {
            /** @description Validation report (valid may be false) */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ConfigValidateResponse"];
                };
            };
            /** @description Document does not parse / carries infra sections */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Authenticated but the principal's role is insufficient (RBAC). */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Unknown organization */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    applyOrganizationConfig: {
        parameters: {
            query?: never;
            header?: {
                /** @description Optimistic concurrency against this org's current document sha. */
                "If-Match"?: string;
                /** @description Audit label (e.g. a git SHA). */
                "X-Config-Revision"?: string;
            };
            path: {
                /** @description Organization id ([[organizations]].id). */
                id: string;
            };
            cookie?: never;
        };
        /** @description Complete desired-state document for this organization (YAML or TOML). */
        requestBody: {
            content: {
                "application/yaml": string;
                "application/toml": string;
            };
        };
        responses: {
            /** @description Applied (or idempotent no-op) */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ConfigApplyResponse"];
                };
            };
            /** @description Document does not parse / carries forbidden sections */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Authenticated but the principal's role is insufficient (RBAC). */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Unknown organization, or [config_api].api_config is off */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description source = "local" pins desired state to Git */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description If-Match precondition failed */
            412: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Document parsed but the composed runtime failed validation */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    rollbackOrganizationConfig: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Organization id ([[organizations]].id). */
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Rolled back */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ConfigApplyResponse"];
                };
            };
            /** @description Authenticated but the principal's role is insufficient (RBAC). */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Unknown organization, or [config_api].api_config is off */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description No earlier applied revision in this stream, or source = "local" */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
}
